### ISSUE TITLE
Fixs en select "Seleccionar cliente"

### ISSUE THREAD

**Issue by eddiezombie** [stgoymz/mx-tracking#1]
- [x] Al momento de presionar el boton "generar" y no haber seleccionado nada, se va a blanco.

- [x] Que el mensaje "wena" se elimine si selecciono otro informe, para saber si se genero el nuevo. (¿Se entiende?)

- [x] Agregar un gif para ver que está cargando.

**Comment by stgoymz** [comment]
se bloqueo el botón si no se selecciona nada.

**Comment by stgoymz** [comment]
se resolvieron los pendientes
